### ISSUE TITLE
Create a drafts backend service

### ISSUE THREAD

**Issue by davidmeirlevy** [greenpress/drafts-service#1]
The ability for editors and admins to save and retrieve drafts, including key and metadata.
indexed by user, tenant, and draft key.
metadata is a non-strict object.

**Comment by ShiraRotman** [comment]
Shouldn't this be part of the content service? The only difference between a post and a draft is a boolean field.

**Comment by davidmeirlevy** [comment]
A draft is used for editors only, and it’s only for the admin panel, and should store any kind of object, such as categories, menus, configs, etc..
No need that it will be stored with the content.

**Comment by itays123** [comment]
What is the required schema?
I suggest this one:
```js
{
  content: String, // required
  title: String, // default: 'Untitled article'
  thumbnail: String
}
```

**Comment by davidmeirlevy** [comment]
the draft schema should have the identifier of the user, tenant, context (post, menu, category, etc..), the identifier of the context (posted, category id, or null if it's a new item).
and a "mixed" metadata that should be any kind of object.. it used directly for the admin panel, and the admin panel should save any draft it needs.

**Comment by itays123** [comment]
Do we need to add info to the API kit?

**Comment by davidmeirlevy** [comment]
yes. there are issues about it in the `greenpress/api-kit` repository.
